import View from '@/components/attendance/View'
import CreateAttendance from '@/components/modals/CreateAttendance'
import Navbar from '@/components/nav/Navbar'
import Sidebar from '@/components/sidebar/Sidebar'
import { authenticate } from '@/utils/authenticate'
import { database } from '@/utils/firebase'
import { onValue, ref } from 'firebase/database'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { toast } from 'react-hot-toast'
import { ClipLoader } from 'react-spinners'

const Attendance = () => {
    const [isLoading, setIsLoading] = useState(false)
    const [showCreateAttendance, setShowCreateAttendance] = useState(false)
    const [filters, setFilters] = useState(new Date().getFullYear())
    const [employees, setEmployees] = useState([])
    const [employee, setEmployee] = useState({})

    const fetchEmployees = async () => {
        setIsLoading(true)
        try {
            onValue(ref(database, 'attendance/' + filters), (snapshot) => {
                let data = []
                snapshot.forEach((childSnapshot) => {
                    const childData = childSnapshot.val();
                    data.push(childData)
                });
                setEmployees(data)
            }, {
                onlyOnce: false
            });
            setIsLoading(false)
        } catch (error) {
            toast.error('Something went wrong.')
            setIsLoading(false)
            console.log(error)
        }
    }

    useEffect(() => {
        fetchEmployees()
    }, [filters])

    const handleDelete = async (expenseId) => {

    }

    return (
        <div>
            <Head>
                <title>Attendance - GM School And Colleges Of Sciences</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar />
                <div className="flex">
                    <Sidebar currentPage={'Attendance'} />
                    <div className="flex w-full lg:w-auto lg:flex-1 flex-col p-4 md:p-5">
                        <section className="bg-gray-50 border border-gray-100 rounded-md">
                            <div className="mx-auto max-w-screen-xl">
                                <div className="bg-white relative shadow-md sm:rounded-lg overflow-hidden">
                                    <div className="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
                                        <div className="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
                                            <div className="flex gap-3 items-center flex-wrap">
                                                <input onChange={(e) => setFilters(new Date(e.target.value).getFullYear())} value={filters.startedDate} name='startedDate' type="date" className='base__input py-[5px] px-3 mt-0 border-gray-100 bg-white text-sm' />

                                            </div>
                                        </div>
                                        <div className="">
                                            <button onClick={() => setShowCreateAttendance(prev => !prev)} className='base__button flex items-center gap-3 px-3'>
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                                                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                                                </svg>
                                                <span>
                                                    Add Attendance
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                    <div className="overflow-x-auto">
                                        <table className="w-full text-sm text-left text-gray-500 ">
                                            <thead className="text-xs text-gray-700 uppercase bg-gray-50">
                                                <tr>
                                                    <th scope="col" className="px-4 py-3 min-w-[30px] max-w-[30px]">Srno.</th>
                                                    <th scope="col" className="px-4 py-3">ID</th>
                                                    <th scope="col" className="px-4 py-3">Name</th>
                                                    <th scope="col" className="px-4 py-3">CNIC</th>
                                                    <th scope="col" className="px-4 py-3">Age</th>
                                                    <th scope="col" className="px-4 py-3">Qualification</th>
                                                    <th scope="col" className="px-4 py-3">Date</th>
                                                    {/* <th scope="col" className="px-4 py-3"></th> */}
                                                    <th scope="col" className="px-4 py-3">
                                                        <span className="sr-only">Actions</span>
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {employees?.map((employee, i) => (
                                                    <EmployeeRow setEmployee={setEmployee} employee={employee} key={employee.name + i.toString()} i={i + 1} />
                                                ))}
                                            </tbody>
                                        </table>
                                        {isLoading && <div className='p-5 flex flex-1 justify-center items-center '>
                                            <ClipLoader
                                                color="orange"
                                                cssOverride={{}}
                                                size={35}
                                                speedMultiplier={1}
                                            />
                                        </div>}
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
                {showCreateAttendance && <CreateAttendance setShowCreateAttendance={setShowCreateAttendance} />}
                {Object.keys(employee).length>0&& <View setEmployee={setEmployee} employee={employee} />}
            </main>
        </div>
    )
}

export default Attendance

export async function getServerSideProps(context) {
    authenticate(context)

    return {
        props: {}
    }
}

const EmployeeRow = ({ employee, i, setEmployee }) => {

    return (
        <tr className="border-b animate-slow">
            <th scope="row" className="px-4 py-3 font-medium text-gray-900 max-w-[30px]">{i}</th>
            <td className="px-4 py-3">
                {employee.id}
            </td>
            <td className="px-4 py-3">{employee.name}</td>
            <td className="px-4 py-3">{employee.cnic}</td>
            <td className="px-4 py-3">{employee.age}</td>
            <td className="px-4 py-3">{employee.qualification}</td>

            <td className="px-4 py-3">{employee.date}</td>
            <td className="px-4 py-3 flex items-center justify-end">
                <div className="flex">
                    <div onClick={()=> setEmployee(employee)} className='text-blue-500 cursor-pointer'>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                            <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                        </svg>
                    </div>
                </div>
            </td>
        </tr>

    )
}