import Navbar from '@/components/nav/Navbar'
import Sidebar from '@/components/sidebar/Sidebar'
import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>GM School And Colleges Of Sciences</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <main className=''>
                <Navbar />
                <div className="flex">
                    <Sidebar currentPage='Employees' />
                    <div className="flex-1 p-5">
                        <div className="flex justify-between">
                            <div className="flex">
                                <div className="flex">
                                    <input type="search" placeholder='Search' className='base__search' />
                                </div>
                            </div>
                            <div className="flex">
                                <button className='base__button'>
                                    <div className='mr-2'>
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                                            <path strokeLinecap="round" strokeLinejoin="round" d="M19 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zM4 19.235v-.11a6.375 6.375 0 0112.75 0v.109A12.318 12.318 0 0110.374 21c-2.331 0-4.512-.645-6.374-1.766z" />
                                        </svg>

                                    </div>
                                    Add Employee
                                </button>
                            </div>
                        </div>
                        <div className="flex mt-4">
                        <table className="w-full text-sm text-left text-gray-500">
                                <thead className="text-xs text-gray-700 uppercase bg-gray-50">
                                    <tr>
                                        <th className="px-6 py-3 font-roboto">
                                            Name
                                        </th>
                                        <th className="px-6 py-3 font-roboto">
                                            Phone
                                        </th>
                                        <th className="px-6 py-3 font-roboto">
                                            Class
                                        </th>
                                        <th className="px-6 py-3 font-roboto">
                                            Medium
                                        </th>
                                        <th className="px-6 py-3 font-roboto">
                                            R.No
                                        </th>
                                        <th className="px-1 py-3 font-roboto">
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <EmployeeRow />
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}



const EmployeeRow = ({}) => {
    return (
        <>
            <tr className="bg-white border-b hover:bg-gray-50 ">
                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap flex items-center">
                    <img className='h-10 w-10 mr-2 rounded object-cover' src={'/avatar.png'} alt='' /> asnkdjn
                </th>
                <td className="px-6 py-4">
                    Meodnad
                </td>
                <td className="px-6 py-4">
                10
                </td>
                <td className="px-6 py-4">
                asd
                </td>
                <td className="px-6 py-4">
                adasd
                </td>
                <td className="px-1 py-4">
                    <div className='hover:bg-gray-100 w-8 h-8 flex justify-center active:bg-gray-300 hover:shadow items-center text-black rounded-full cursor-pointer'>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M12 6.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 12.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 18.75a.75.75 0 110-1.5.75.75 0 010 1.5z" />
                        </svg>
                    </div>
                </td>
            </tr>
        </>
    )
} 