import CreateStudent from '@/components/modals/CreateStudent'
import ViewStudent from '@/components/modals/ViewStudent'
import Navbar from '@/components/nav/Navbar'
import Sidebar from '@/components/sidebar/Sidebar'
import axios from 'axios'
import Head from 'next/head'
import React, { useEffect, useState } from 'react'

const Students = () => {
    const [showCreateStudent, setShowCreateStudent] = useState(false)
    const [students, setStudents] = useState([])
    const [viewStudent, setViewStudent] = useState({})

    useEffect(() => {
        const fetchStudents = async () => {
            const res = await axios.get('/api/student/getall')
            setStudents(res.data)
        }
        fetchStudents()
    }, [])


    return (
        <>
            <Head>
                <title>Students - GM School And Colleges Of Sciences</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <main className=''>
                <Navbar />
                <div className="flex">
                    <Sidebar currentPage={'Students'} />
                    <div className="flex-1 p-5">
                        <div className='flex justify-between mb-4'>
                            <div className="flex space-x-3">

                                <select className='base__select'><option value=''>Select Class</option>
                                    <option value="classnursery">Nursery Red</option>
                                    <option value="classnurseryblue">Nursery Blue</option>

                                    <option value="classprep">Prep</option>

                                    <option value="classpg">PG Red</option>
                                    <option value="classpgblue">PG Blue</option>
                                    <option value="classpggreen">PG Green</option>

                                    <option value="classkg1">KG1 Red</option>
                                    <option value="classkg1blue">KG1 Blue</option>
                                    <option value="classkg1green">KG1 Green</option>

                                    <option value="classkg2">KG2 Red</option>
                                    <option value="classkg2blue">KG2 Blue</option>
                                    <option value="classkg2green">KG2 Green</option>

                                    <option value="class1">Class 1 Red</option>
                                    <option value="class1blue">Class 1 Blue</option>
                                    <option value="class1green">Class 1 Green</option>

                                    <option value="class1english">Class 1 E.M</option>
                                    <option value="class1urdu">Class 1 U.M</option>

                                    <option value="class2">Class 2 E.M</option>
                                    <option value="class2urdu">Class 2 U.M</option>

                                    <option value="class3">Class 3 E.M</option>
                                    <option value="class3urdu">Class 3 U.M</option>

                                    <option value="class4">Class 4 E.M</option>
                                    <option value="class4urdu">Class 4 U.M</option>

                                    <option value="class5">Class 5 E.M</option>
                                    <option value="class5urdu">Class 5 U.M</option>

                                    <option value="class6">Class 6 E.M</option>
                                    <option value="class6urdu">Class 6 U.M</option>

                                    <option value="class7">Class 7 E.M</option>
                                    <option value="class7urdu">Class 7 U.M</option>

                                    <option value="class8">Class 8 E.M</option>
                                    <option value="class8urdu">Class 8 U.M</option>

                                    <option value='classpre9' >Class Pre-9</option>
                                    <option value='class9' >Class 9 E.M</option>
                                    <option value='class9urdu' >Class 9 U.M</option>

                                    <option value="class10">Class 10 E.M</option>
                                    <option value="class10urdu">Class 10 U.M</option>
                                </select>

                                <select className='base__select'>
                                    <option value="">Select Session</option>
                                    <option value="" className='dropbt'>2021</option>
                                    <option value="" className='dropbt'>2022</option>
                                    <option value="" className='dropbt'>2023</option>
                                    <option value="" className='dropbt'>2024</option>
                                    <option value="" className='dropbt'>2025</option>
                                    <option value="" className='dropbt'>2026</option>
                                    <option value="" className='dropbt'>2027</option>
                                    <option value="" className='dropbt'>2028</option>
                                    <option value="" className='dropbt'>2029</option>
                                    <option value="" className='dropbt'>2030</option>
                                    <option value="" className='dropbt'>2031</option>
                                </select>

                                <button className='base__button'>Apply</button>
                            </div>
                            <div className="">
                                <button className='base__button' onClick={() => setShowCreateStudent(true)} title='Add Student'>
                                    <div className='mr-2'>
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                                            <path strokeLinecap="round" strokeLinejoin="round" d="M19 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zM4 19.235v-.11a6.375 6.375 0 0112.75 0v.109A12.318 12.318 0 0110.374 21c-2.331 0-4.512-.645-6.374-1.766z" />
                                        </svg>

                                    </div>
                                    Add Student
                                </button>
                            </div>
                        </div>
                        <div className="relative overflow-x-auto shadow sm:rounded-lg">
                            <table className="w-full text-sm text-left text-gray-500">
                                <thead className="text-xs text-gray-700 uppercase bg-gray-50">
                                    <tr>
                                        <th className="px-6 py-3 font-roboto">
                                            Name
                                        </th>
                                        <th className="px-6 py-3 font-roboto">
                                            Father Name
                                        </th>
                                        <th className="px-6 py-3 font-roboto">
                                            Class
                                        </th>
                                        <th className="px-6 py-3 font-roboto">
                                            Medium
                                        </th>
                                        <th className="px-6 py-3 font-roboto">
                                            R.No
                                        </th>
                                        <th className="px-1 py-3 font-roboto">
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {students.map((stu) => (
                                        <StudentRow student={stu} key={stu._id} setViewStudent={setViewStudent} />
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                {showCreateStudent && <CreateStudent setShowCreateStudent={setShowCreateStudent} />}
                {Object.keys(viewStudent).length>0&&<ViewStudent viewStudent={viewStudent} setViewStudent={setViewStudent} />}
            </main>
        </>
    )
}

export default Students

const StudentRow = ({ student, setViewStudent }) => {
    const [showMenu, setShowMenu] = useState(false)

    return (
        <>
            <tr className="bg-white border-b hover:bg-gray-50" title={student.name}>
                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap flex items-center">
                    <img className='h-10 w-10 mr-2 rounded object-cover' src={student.picture ? student.picture : '/avatar.png'} alt={student.name} /> {student.name}
                </th>
                <td className="px-6 py-4">
                    {student.fathername}
                </td>
                <td className="px-6 py-4">
                    10
                </td>
                <td className="px-6 py-4">
                    {student.medium}
                </td>
                <td className="px-6 py-4">
                    {student.rn}
                </td>
                <td className="px-1 py-4 relative">
                    <div onClick={() => setShowMenu(prev => !prev)} className='hover:bg-gray-100 w-8 h-8 flex justify-center active:bg-gray-300 hover:shadow items-center text-black rounded-full cursor-pointer'>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M12 6.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 12.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 18.75a.75.75 0 110-1.5.75.75 0 010 1.5z" />
                        </svg>
                    </div>
                    <div className={`absolute py-2 rounded bg-white transition-all duration-300 ease-in-out flex flex-col space-y-1 shadow ${showMenu ? 'scale-100 top-10 right-[54px]' : 'scale-0 top-5 right-5'}`}>
                        <div onClick={()=> setViewStudent(student)} className='flex space-x-3 px-3 py-1 hover:bg-gray-100 cursor-pointer'>
                            <div>
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                </svg>
                            </div>
                            <div>View</div>
                        </div>
                        <div className='flex space-x-3 px-3 py-1 hover:bg-gray-100 cursor-pointer'>
                            <div>
                                <svg className='w-4 h-4' xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
                                </svg>

                            </div>
                            <div>Edit</div>
                        </div>
                    </div>
                </td>
            </tr>
        </>
    )
} 